[dev]
port = 3000
ws_port = 3001

[site]
script_urls = []

style_urls = [
  'https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css',
  'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism-tomorrow.min.css'
]

[meta]
title = "Mextron"
description = "Blazing fast static site generator written in Rust"
og_image_url = "https://avaterclasher.github.io/mextron/images/og.png"
base_url = "https://avaterclasher.github.io/mextron/"


[navigation] 
links = [
    { label = "~/", url = "/" },
    { label = "Blog", url = "/blog/"},
    { label = "About", url = "/about/"},
    { label = "GitHub", url = "https://github.com/AvaterClasher/mextron" },
    { label = "Website", url = "https://soumyadipmoni.netlify.app" },
]

[data]
author = "Soumyadip Moni"
author_link = "https://github.com/AvaterClasher"

[remote_data]
repo_meta = "https://api.github.com/repos/AvaterClasher/mextron"