[dev]
port = 3000

[site]
code_highlighting = true

[meta]
title = "Mextron"

description = "Blazing fast static site generator written in Rust"


top_navigation = [
    { label = "~/", url = "/" },
    { label = "GitHub", url = "https://github.com/AvaterClasher/mextron" },
    { label = "Website", url = "https://soumyadipmoni.netlify.app" },
]