[dev]
port = 3000

[site]
title = "Mextron"
description = "Blazing fast static site generator written in Rust"
top_navigation = [
    { label = "About", url = "/about" },
    { label = "GitHub", url = "https://github.com/AvaterClasher/mextron" },
    { label = "Website", url = "https://soumyadipmoni.netlify.app" },
]