[dev]
port = 3000

[site]
script_urls = []

style_urls = [
  'https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css',
  'https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;700&display=swap',
]

[meta]
title = "Mextron"
description = "Blazing fast static site generator written in Rust"
og_image_url = "https://avaterclasher.github.io/mextron/images/og.png"
base_url = "https://avaterclasher.github.io/mextron/"


[navigation] 
links = [
    { label = "~/", url = "/" },
    { label = "Blog", url = "/blog/"},
    { label = "About", url = "/about/"},
    { label = "GitHub", url = "https://github.com/AvaterClasher/mextron" },
    { label = "Website", url = "https://soumyadipmoni.netlify.app" },
]