[dev]
port = 3000

[site]
code_highlighting = true
sitemap_base_url = "https://avaterclasher.github.io/mextron/"

[meta]
title = "Mextron"
description = "Blazing fast static site generator written in Rust"


[navigation] 
links = [
    { label = "~/", url = "/" },
    { label = "Blog", url = "/blog"},
    { label = "About", url = "/about"},
    { label = "GitHub", url = "https://github.com/AvaterClasher/mextron" },
    { label = "Website", url = "https://soumyadipmoni.netlify.app" },
]